# Generated by Django 5.2.5 on 2025-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Status to check if the entity is active'),
        ),
    ]
