# Generated by Django 5.2.5 on 2025-08-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_student_id_alter_student_is_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportcard',
            name='report_card_year_5c8a33_idx',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='is_published',
        ),
    ]
